HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt beep
bindkey -v
SCHOOL="jdn4257@glados.cs.rit.edu"
export EDITOR='vim'
alias ls='ls --color=auto'
alias lss='ls --color=auto -lAh'
alias cls='clear && ls --color=auto'
alias clss='clear && ls --color=auto -lAh'
if [ "$(tty)" = "/dev/tty1" ]; then
  echo -e "\033[1m\033[32mRun the sway command to get graphical.\033[0m"
fi
